sampleSizeTightened = {
              'A': {'sampleQty': 2,
                    'aql-1': {'accept': 0, 'reject': 1},
                    'aql-1.5': {'accept': 0, 'reject': 1},
                    },
              'B': {'sampleQty': 3,
                    'aql-1': {'accept': 0, 'reject': 1},
                    'aql-1.5': {'accept': 0, 'reject': 1},
                    },          
              'C': {'sampleQty': 5,
                    'aql-1': {'accept': 0, 'reject': 1},
                    'aql-1.5': {'accept': 0, 'reject': 1},
                    },
              'D': {'sampleQty': 8,
                    'aql-1': {'accept': 0, 'reject': 1},
                    'aql-1.5': {'accept': 0, 'reject': 1},
                    },
              'E': {'sampleQty': 13,
                    'aql-1': {'accept': 0, 'reject': 1},
                    'aql-1.5': {'accept': 0, 'reject': 1},
                    },
              'F': {'sampleQty': 20,
                    'aql-1': {'accept': 0, 'reject': 1},
                    'aql-1.5': {'accept': 1, 'reject': 2},
                    },
              'G': {'sampleQty': 32,
                    'aql-1': {'accept': 1, 'reject': 2},
                    'aql-1.5': {'accept': 1, 'reject': 2},
                    },
              'H': {'sampleQty': 50,
                    'aql-1': {'accept': 1, 'reject': 2},
                    'aql-1.5': {'accept': 1, 'reject': 2},
                    },
              'J': {'sampleQty': 80,
                    'aql-1': {'accept': 1, 'reject': 2},
                    'aql-1.5': {'accept': 2, 'reject': 3},
                    },
              'K': {'sampleQty': 125,
                    'aql-1': {'accept': 2, 'reject': 3},
                    'aql-1.5': {'accept': 3, 'reject': 4},
                    },
              'L': {'sampleQty': 200,
                    'aql-1': {'accept': 3, 'reject': 4},
                    'aql-1.5': {'accept': 5, 'reject': 6},
                    },
              'M': {'sampleQty': 315,
                    'aql-1': {'accept': 5, 'reject': 6},
                    'aql-1.5': {'accept': 8, 'reject': 9},
                    },
              'N': {'sampleQty': 500,
                    'aql-1': {'accept': 8, 'reject': 9},
                    'aql-1.5': {'accept': 12, 'reject': 13},
                    },
              'P': {'sampleQty': 800,
                    'aql-1': {'accept': 12, 'reject': 13},
                    'aql-1.5': {'accept': 18, 'reject': 19},
                    },
              'Q': {'sampleQty': 1250,
                    'aql-1': {'accept': 18, 'reject': 19},
                    'aql-1.5': {'accept': 18, 'reject': 19},
                    },
              'R': {'sampleQty': 2000,
                    'aql-1': {'accept': 10, 'reject': 11},
                    'aql-1.5': {'accept': 10, 'reject': 11},
                    }           
              }
